windowSizeComment: "halfAvailable | fullAvailable | partAvailable"
windowSize: partAvailable

MwindowSizeComment: "or manual. ~ if default"
MwindowSize: ~

frameLimit: ~

antialiasingLevel: 2

pointCount: ~

dpInWindowComment: "1000 usually"
dpInWindow: 1000

offset: 0.1

fontFile: font.otf
